name: Publish Packages on release

on:
  # Run when a new release is published, or manually.
  release:
    types: published
  workflow_dispatch:
    branches:
      - master

jobs:
  publish:
    name: Publish Packages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # Configure and publish to NPM
      - uses: actions/setup-node@v1
        with:
          node-version: "12"
          registry-url: "https://registry.npmjs.org"
      - run: npm ci
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      # Configure and publish to GitHub Packages
      - uses: actions/setup-node@v1
        with:
          node-version: "12" 
          registry-url: "https://npm.pkg.github.com/TheThunderGuyS"
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

